microhot_device:
  account: root
  hotdeviceIP: 192.168.238.100
  default_gateway: 192.168.238.2
  gateway_66: 192.168.66.1
  PASSWORD: '$9@!&*(!7@#n?'
  MACHINE_PASSWORD: 'cewisec_2019'
  default_band: '192.168.66.'
detect_code:
  base_url: http://113.108.109.221:49191
  version_management:
    upload: /CriminalCode-admin-web/file/upload
    add: /CriminalCode-admin-web/version/add
    download: /CriminalCode-admin-web/file/download/
    query: /CriminalCode-admin-web/version/query
    push: /CriminalCode-admin-web/version/push
    querypush: /CriminalCode-admin-web/version/queryPush/
    query_push_record: /CriminalCode-admin-web/version/queryPushRecord
    delete_versionid: /CriminalCode-admin-web/version/delete/